YSHOP2-1216: Added DropdownMenu component
youcan-shop/youcan-ui pull request #245
Opened 2024-01-24 10:06 UTC by GhitaNektt

## JIRA Ticket

[YSHOP2-1216](https://youcanshop.atlassian.net/browse/YSHOP2-1216)

## QA Steps

* [ ] Go to http://localhost:3000/
* [ ] Check the Dropdown menu

## Note

Leave empty when you have nothing to say

2024-01-25 13:41 UTC, eihabkhan1 commented on packages/vue3/src/components/DropdownMenu/DropdownMenu.vue
> +const toggleMenu = () => {
Always separate refs from others

2024-01-29 10:07 UTC, mosarabi requested changes

2024-01-29 10:07 UTC, mosarabi commented on packages/vue3/src/components/DropdownMenu/DropdownMenu.vue
> +onClickOutside(DropdownMenuContainer, () => show.value = false);
```suggestion
const handleScroll = () => {
  show.value = false;
};

onMounted(() => {
  window.addEventListener('scroll', handleScroll);
});

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll);
});

onClickOutside(DropdownMenuContainer, () => show.value = false);
```

2024-01-29 10:07 UTC, mosarabi commented on packages/vue3/src/components/DropdownMenu/DropdownMenu.vue
> +import { nextTick, ref } from 'vue';
```suggestion
import { nextTick, ref, onMounted, onUnmounted} from 'vue';
```

2024-01-29 10:07 UTC, mosarabi commented on packages/vue3/src/components/DropdownMenu/DropdownMenu.vue
> +onClickOutside(DropdownMenuContainer, () => show.value = false);
would you mind to add scroll event to hide menu when user start scrolling

2024-01-29 10:23 UTC, mosarabi requested changes

2024-01-29 10:23 UTC, mosarabi commented on packages/vue3/src/components/DropdownMenu/DropdownMenuTrigger.vue
> +</style>
I think no need to create this component 
What d u think?

2024-01-29 10:32 UTC, eihabkhan1 commented
Can we set the cursor to pointer on the items

2024-01-29 10:33 UTC, GhitaNektt commented
> Can we set the cursor to pointer on the items

yeah sure

2024-01-29 11:15 UTC, merged