UI-243 : Added rich text component with quill
youcan-shop/youcan-ui pull request #285
Opened 2024-03-01 10:10 UTC by GhitaNektt

## JIRA Ticket

[UI-243](https://youcanshop.atlassian.net/browse/UI-243)

## QA Steps

* [ ] Go to X and Y
* [ ] See TEXT in page Z

## Note

Leave empty when you have nothing to say

2024-03-04 08:57 UTC, eihabkhan1 commented
Issues I found while using RichText:
- Toolbar is not sticky, when the content is long, the toolbar doesn't stick
- Italic style only working when the text is bold
- "T" icon should change to something that represents 
- `webp` and `avif` images are not supported
- Can only upload videos from a link, can't upload a video from local machine

2024-03-04 08:57 UTC, eihabkhan1 requested changes

2024-03-04 08:57 UTC, eihabkhan1 commented on packages/vue3/src/components/RichText/EditorToolbar.ts
Seems like we are missing the `x-100` color degree from each color (e.g `brand-100`, `gray-100`, etc)

2024-03-04 08:57 UTC, eihabkhan1 commented on packages/vue3/src/components/RichText/ToolbarIcons.ts
> +  'direction': {
We should add a different icon that represents RTL/LTR

2024-03-11 12:07 UTC, eihabkhan1 commented
Seems that we can't delete uploaded images

2024-03-15 15:56 UTC, mosarabi requested changes
https://github.com/youcan-shop/youcan-ui/assets/149577299/2bcb473a-e86f-48ac-a55d-926e97fb7901

The Quill Editor block does not function correctly in RTL mode

2024-03-15 15:59 UTC, GhitaNektt commented
Try configuring the direction in the code prior to mounting the component.

2024-03-16 11:38 UTC, mosarabi approved these changes

2024-03-18 10:45 UTC, merged